easy_admin:
  entities:
    # Product:
    #   class: App\Entity\Product
    #   label: "Product"
    #   list:
    #     collapse_actions: true
    #     actions: ['show', 'edit', 'delete']
    #     batch_actions: ['delete']
    #     fields: ['title', 'content', 'createdAt', {property: 'thumbnail', type: 'image', base_path: '%uploads_path%'}]